# coding: utf-8

"""
    Sample Application Flow OAuth2 Project

    This is an example of using OAuth2 Application Flow in a specification to describe security to your API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_example_get(self):
        """Test case for example_get

        Server example operation  # noqa: E501
        """
        pass

    def test_ping_get(self):
        """Test case for ping_get

        Server heartbeat operation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
